- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: test
      name: vicKey
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: moto
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
